spring.application.name=javaapi


# DATABASE
#default
spring.datasource.url=jdbc:postgresql://ep-holy-tree-a73c5hxl-pooler.ap-southeast-2.aws.neon.tech:5432/neondb?sslmode=require&channel_binding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_BZoR1yG0QPHY
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect