name: Notify Discord on Push

on: [push]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Notify Discord
        uses: peter-evans/discord-webhook@v1
        with:
          webhook-url: ${{ secrets.DISCORD_WEBHOOK }}
          message: "🚀 New push to **${{ github.repository }}** by `${{ github.actor }}`"

